name: budget_app
description: A budget app to categorize my expenses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-45.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  path: ^1.8.1
  charts_flutter: ^0.12.0
  sleek_circular_slider: ^2.0.1
  intl: ^0.17.0
  random_color: ^1.0.6-nullsafety
  tuple: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

